import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  notesSidebar: [
    {
      type: 'category',
      label: 'Unreal Engine',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'unreal-engine'}],
    },
    {
      type: 'category',
      label: 'C++',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'cpp'}],
    },
    {
      type: 'category',
      label: 'Graphics',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'graphics'}],
    },
    {
      type: 'category',
      label: 'Tools',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'tools'}],
    },
    {
      type: 'category',
      label: 'AI',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'ai'}],
    },
  ],
};

export default sidebars;
